### GET Currencies
GET {{baseUrl}}/currencies

### POST Currency
POST {{baseUrl}}/currencies
Content-Type: application/json

{
  "code": "test123",
  "type": "fiat",
  "amount": 456
}

### POST Conversion
POST {{baseUrl}}/convert
Content-Type: application/json

{
  "from": "USD",
  "to": "EUR",
  "amount": 1
}