FROM node:18.15.0-slim AS base
WORKDIR /app

FROM base AS build
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM base AS production
ENV NODE_ENV=production
COPY package*.json .
RUN npm ci --only=production
COPY --from=build /app/dist ./dist
CMD ["node", "dist/main.js"]